### ISSUE TITLE
search track

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/switch-to-spotify#3]
### Description

The goal is to get a spotify id by an id3 tag

### Subtasks

- [ ] async query to get an id
- [ ] minimalize the result, but get a result nonetheless by trying with less parameters
- [ ] collect tags, which didn't yield a result
